### ISSUE TITLE
Info: Plans

### ISSUE THREAD

**Issue by fede-exe** [igniter-labs/ti-ext-importexport#1]
Any plans to complete this amazing extension?:)
Really needed to upload big menù

**Comment by sampoyigi** [comment]
Erm, I would try it out with fingers crossed lol.. All that's left at this stage is some refactoring and minor bug fixes, it could work. 🤞

**Comment by fede-exe** [comment]
It didn't work with me because I couldn't choose what to take or upload from the dropdown menu.

**Comment by sampoyigi** [comment]
Works for me.

<img width="564" alt="Screenshot 2020-04-09 at 10 04 04" src="https://user-images.githubusercontent.com/6567634/78878090-ba98d180-7a49-11ea-9cf2-bba2a9fe1876.png">

<img width="1207" alt="Screenshot 2020-04-09 at 10 05 23" src="https://user-images.githubusercontent.com/6567634/78878041-a94fc500-7a49-11ea-9c73-e9ebefc7aea4.png">

**Comment by sampoyigi** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please reopen if it still occurs.
