### ISSUE TITLE
Bug: Import Errror

### ISSUE THREAD

**Issue by fede-exe** [igniter-labs/ti-ext-importexport#3]
After selecting IMPORT RECORDS and import menu items -> Continue got this error.

RuntimeException
SplFileObject::__construct(/homepages/1/d824198440/htdocs/storage/temp/ti-import-101be68105d41ae94445b62a81f091ff.csv): failed to open stream: No such file or directory

04-13 09:49:03 | RuntimeException: SplFileObject::__construct(/homepages/1/d824198440/htdocs/storage/temp/ti-import-101be68105d41ae94445b62a81f091ff.csv): failed to open stream: No such file or directoryin /homepages/1/d824198440/htdocs/vendor/league/csv/src/AbstractCsv.php:271Stack trace:#0 /homepages/1/d824198440/htdocs/vendor/league/csv/src/AbstractCsv.php(271): SplFileObject->__construct('/homepages/1/d8...', 'r')#1 /homepages/1/d824198440/htdocs/vendor/league/csv/src/AbstractCsv.php(253): League\Csv\AbstractCsv->setIterator()#2 /homepages/1/d824198440/htdocs/vendor/league/csv/src/Modifier/QueryFilter.php(160): League\Csv\AbstractCsv->getIterator()#3 /homepages/1/d824198440/htdocs/vendor/league/csv/src/Reader.php(119): League\Csv\AbstractCsv->getQueryIterator()#4 /homepages/1/d824198440/htdocs/extensions/igniter/importexport/actions/ImportController.php(209): League\Csv\Reader->fetchOne(0)#5 /homepages/1/d824198440/htdocs/extensions/igniter/importexport/actions/ImportController.php(183): Igniter\ImportExport\Actions\ImportController->getImportFileColumns()#6 /homepages/1/d824198440/htdocs/extensions/igniter/importexport/actions/ImportController.php(173): Igniter\ImportExport\Actions\ImportController->prepareImportVars()#7 /homepages/1/d824198440/htdocs/extensions/igniter/importexport/actions/ImportController.php(79): Igniter\ImportExport\Actions\ImportController->initImportForms()#8 [internal function]: Igniter\ImportExport\Actions\ImportController->import('import', 'igniter-local-m...')#9 /homepages/1/d824198440/htdocs/vendor/tastyigniter/flame/src/Traits/ExtendableTrait.php(384): call_user_func_array(Array, Array)#10 /homepages/1/d824198440/htdocs/vendor/tastyigniter/flame/src/Support/Extendable.php(42): Igniter\Flame\Support\Extendable->extendableCall('import', Array)#11 [internal function]: Igniter\Flame\Support\Extendable->__call('import', Array)#12 /homepages/1/d824198440/htdocs/app/admin/classes/AdminController.php(206): call_user_func_array(Array, Array)#13 /homepages/1/d824198440/htdocs/app/admin/classes/AdminController.php(168): Admin\Classes\AdminController->execPageAction('import', Array)#14 /homepages/1/d824198440/htdocs/app/system/classes/Controller.php(110): Admin\Classes\AdminController->remap('import', Array)#15 [internal function]: System\Classes\Controller->runAdmin('igniter/importe...')#16 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)#17 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('runAdmin', Array)#18 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(System\Classes\Controller), 'runAdmin')#19 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()#20 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Route->run()#21 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#22 /homepages/1/d824198440/htdocs/vendor/tastyigniter/flame/src/Currency/Middleware/CurrencyMiddleware.php(33): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#23 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Currency\Middleware\CurrencyMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))#24 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#25 /homepages/1/d824198440/htdocs/app/admin/middleware/LogUserLastSeen.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#26 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Admin\Middleware\LogUserLastSeen->handle(Object(Illuminate\Http\Request), Object(Closure))#27 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#28 /homepages/1/d824198440/htdocs/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(23): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#29 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))#30 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#31 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#32 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))#33 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#34 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#35 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))#36 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#37 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#38 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))#39 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#40 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#41 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))#42 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#43 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#44 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))#45 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#46 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#47 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))#48 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))#49 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))#50 /homepages/1/d824198440/htdocs/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))#51 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))#52 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))#53 /homepages/1/d824198440/htdocs/extensions/igniter/cart/middleware/CartMiddleware.php(10): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#54 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Cart\Middleware\CartMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))#55 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#56 /homepages/1/d824198440/htdocs/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#57 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Igniter\Flame\Setting\Middleware\SaveSetting->handle(Object(Illuminate\Http\Request), Object(Closure))#58 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#59 /homepages/1/d824198440/htdocs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#60 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))#61 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#62 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#63 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))#64 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#65 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#66 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))#67 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#68 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#69 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))#70 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))#71 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))#72 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))#73 /homepages/1/d824198440/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))#74 /homepages/1/d824198440/htdocs/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))#75 {main}
-- | --

**Comment by sampoyigi** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please reopen if it still occurs.
