### ISSUE TITLE
Missing locations attribute in import / export menu.

### ISSUE THREAD

**Issue by fede-exe** [igniter-labs/ti-ext-importexport#5]
In this way if you import an item it is attributed to all the restaurants.

If this is added would really help also add this: 
https://github.com/tastyigniter/ti-ext-importexport/issues/4#issue-598786043

**Comment by fede-exe** [comment]
@sampoyigi no chance? you are the only one who can add this feature, we have tried several without success.

Thanks

**Comment by sampoyigi** [comment]
@fede-exe Nope, I'm not the only one who can add the feature, it is open-sourced so that you can send PR to add features or fix bugs. I can definitely help if you are stuck, share what you've tried here or start a discussion on the forum to get help.

**Comment by fede-exe** [comment]
I'm stuck, as other users can't help with this, so I asked for your help. I tried adding in the local extensions> model> menuimport.php

something to make the relation of the item to the location like:


`    'morphToMany' => [
            'locations' => ['Admin\Models\Locations_model', 'name' => 'locationable'],`


but I don't really know which way to go, for example, this is the opinion of another very active user:

> It does connect to the admin model for permissions, then to the db. The problem is it does not have any documentation of the extension so ... without properly documentation it requires a lot of time to comprehend the extension and how it works. That's why he doesn't recommend it usage just yet


so please help me with some advise to implement this function, it's very important @sampoyigi 

Hope you can help, thanks a lot

**Comment by sampoyigi** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please reopen if it still occurs.
